name: Build
on:
  - push
  - pull_request

jobs:
  build-windows:

    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: "Setup MSBuild"
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 17
          msbuild-architecture: x64

      - name: "Build"
        working-directory: ${{github.workspace}}
        run: msbuild Win32DependencyTracker.sln -t:build -restore -p:Configuration=Release -p:RestorePackagesConfig=true

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: Win32DependencyTracker
          path: Win32DependencyTracker/bin/Release/*
